apiVersion: v1
kind: Pod
metadata:
  name: multi-process-container
spec:
  containers:
  - image: quay.io/luksa/multi-process-container:latest
    name: main 
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - /probe.sh
#      exec:
#        command:
#        - sleep
#        - infinity
      timeoutSeconds: 10
      periodSeconds: 10
      failureThreshold: 3
  terminationGracePeriodSeconds: 0

